import fs from 'fs'
import path from 'path'
import Link from 'next/link'
import type { Insight } from '@/lib/types/insights'

const INSIGHTS_DIR = path.join(process.cwd(), 'data', 'insights')

function loadInsights(): Insight[] {
  try {
    if (!fs.existsSync(INSIGHTS_DIR)) return []
    const files = fs.readdirSync(INSIGHTS_DIR).filter((f) => f.endsWith('.json')).sort().reverse()
    return files.slice(0, 20).map((f) => {
      const raw = fs.readFileSync(path.join(INSIGHTS_DIR, f), 'utf-8')
      return JSON.parse(raw) as Insight
    })
  } catch {
    return []
  }
}

const SIGNAL_COLORS = {
  positive: 'text-green-700 bg-green-50',
  negative: 'text-red-700 bg-red-50',
  neutral: 'text-gray-700 bg-gray-50',
}

export default function InsightsPage() {
  const insights = loadInsights()

  return (
    <main className="max-w-screen-lg mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">AI Economic Insights</h1>
        <p className="text-sm text-gray-500 mt-1">
          Generated by Claude Code analyzing real-time macroeconomic data
        </p>
      </div>

      {insights.length === 0 ? (
        <div className="text-center py-16 bg-white rounded-xl border border-gray-200">
          <p className="text-gray-500 font-medium">No insights generated yet</p>
          <p className="text-sm text-gray-400 mt-2">
            Go to{' '}
            <Link href="/admin" className="text-blue-600 hover:underline">
              Admin
            </Link>{' '}
            and click &quot;Generate Insight&quot; to create AI commentary
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {insights.map((insight) => (
            <article key={insight.id} className="bg-white rounded-xl border border-gray-200 p-6">
              <div className="flex items-start justify-between gap-4 mb-3">
                <div>
                  <h2 className="text-lg font-bold text-gray-900">{insight.title}</h2>
                  <p className="text-xs text-gray-400 mt-1">
                    Generated {new Date(insight.generatedAt).toLocaleString()} · Data as of{' '}
                    {new Date(insight.dataSnapshotDate).toLocaleDateString()}
                  </p>
                </div>
                <Link
                  href={`/insights/${insight.id}`}
                  className="text-sm text-blue-600 hover:underline whitespace-nowrap"
                >
                  Read full →
                </Link>
              </div>

              <p className="text-sm text-gray-700 mb-4">{insight.summary}</p>

              {insight.keyMetrics.length > 0 && (
                <div className="flex flex-wrap gap-2 mb-4">
                  {insight.keyMetrics.map((m, i) => (
                    <span
                      key={i}
                      className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ${SIGNAL_COLORS[m.signal]}`}
                    >
                      <strong>{m.name}:</strong> {m.value}
                      {m.change && <span className="opacity-70">({m.change})</span>}
                    </span>
                  ))}
                </div>
              )}

              {insight.outlook && (
                <p className="text-sm text-gray-600 border-l-2 border-blue-200 pl-3 italic">
                  {insight.outlook}
                </p>
              )}
            </article>
          ))}
        </div>
      )}
    </main>
  )
}
